config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show]
  resources :items, only: [:index] do
    member do
      put :add_to_basket
    end
  end

  resources :order_items, only: [:index, :edit, :update, :destroy]

  resource :basket, only: [:destroy, :update] do
    member do
      get :checkout
      get :payment
      put :process_payment
      put :check_discount
    end
  end

  root 'items#index'
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :load_basket

  # Destroy the basket and the session info.
  def destroy
    @basket.destroy
    session.destroy
    flash[:success] = 'Basket emptied successfully'
    redirect_to root_path and return
  end

  # Display the promo codes page.
  def checkout
    @promo_codes = PromoCode.active
    @order_promo_codes = @basket.order_promo_codes
  end

  # Display the payment page. Accept user and credit card details.
  def payment
    @user = @basket.build_user
    @credit_card = @user.credit_cards.build
  end

  # if the payment is successful, update the basket with the confirmed status and destroy the associated session.
  def process_payment
    if @basket.update(basket_payment_params.merge(state: :confirmed))
      session.destroy
      flash[:success] = 'Payment successful'
      redirect_to items_path and return
    end
    @user = @basket.user
    @credit_card = @user.credit_cards.last
    render :payment
  end

  # check the entered promocodes and update the basket to reflect the discount and the final total
  def check_discount
    @basket.order_promo_codes.destroy_all
    if @basket.update(order_promo_codes_params)
      redirect_to checkout_basket_path and return
    else
      @promo_codes = PromoCode.active
      render :checkout
    end
  end

  private

  def load_basket
    @basket = current_basket
  end

  def order_promo_codes_params
    params.fetch(:order).permit(order_promo_codes_attributes: [:promo_code_id, :_destroy])
  end

  def basket_payment_params
    params.fetch(:order).permit(:id, user_attributes: [:email, :address, credit_cards_attributes: [:number, :cvv, :expiry_date]])
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/checkout.html.haml
- if @basket.order_items.count > 0
  %h3
    Checkout the basket
  .row
    .col-md-4
      = simple_nested_form_for(@basket, url: check_discount_basket_path, method: :put) do |f|
        - if @basket.errors.any?
          #error_explanation
            = "#{pluralize(@basket.errors.count, "error")} prohibited the action"
            %ul
              - @basket.errors.full_messages.each do |message|
                %li= message
        = f.input :total, readonly: true
        = f.input :discount, readonly: true
        = f.input :final_total, readonly: true
        = f.simple_fields_for :order_promo_codes, @order_promo_codes do |pf|
          = pf.input :promo_code_id, as: :select, collection: @promo_codes.pluck(:code, :id), prompt: 'Choose a code',
            label: 'Promo Code'
          = pf.link_to_remove 'Remove'
        = f.link_to_add "Add promocode", :order_promo_codes, data: {limit: PromoCode.active.count}
        %div
          = f.button :submit, 'Apply promo codes'
    .col-md-4
      .text
        Move to the Payment page if applied promocodes are satisfactory.
      = link_to 'Make Payment', payment_basket_path, class: 'btn btn-primary'
- else
  Your basket is empty. Please add items.

app/views/baskets/payment.html.haml
- if @basket.order_items.count > 0
  %h3
    Make Payment.
  .row
    .col-md-4
      = simple_nested_form_for(@basket, url: process_payment_basket_path, method: :put) do |f|
        - if @basket.errors.any?
          #error_explanation
            = "#{pluralize(@basket.errors.count, "error")} prohibited this action"
            %ul
              - @basket.errors.full_messages.each do |message|
                %li= message
        = f.input :id, as: :hidden, value: @basket.id
        = f.input :final_total, readonly: true
        %div
          %br
          %h4 Customer Details:
          %div
            = f.fields_for :user, @user do |pf|
              = pf.input :email, as: :email
              = pf.input :address, as: :text
              = pf.fields_for :credit_cards, @credit_card do |ccf|
                = ccf.input :number, label: 'Credit Card Number'
                = ccf.input :cvv
                = ccf.input :expiry_date, as: :date, start_year: Date.today.year, start_month: Date.today.month, start_day: Date.today.day
        %div
          = f.button :submit, 'Make Payment'
- else
  Your basket is empty. Please add items.