config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show]
  resources :items, only: [:index] do
    member do
      put :add_to_basket
    end
  end

  resources :order_items, only: [:index, :edit, :update, :destroy]

  resource :basket, only: [:destroy, :update] do
    member do
      get :checkout
      get :payment
      put :process_payment
      put :check_discount
    end
  end

  root 'items#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  state       :string
#  total       :decimal(8, 2)    default(0.0)
#  discount    :decimal(8, 2)    default(0.0)
#  final_total :decimal(8, 2)    default(0.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Order < ApplicationRecord

  belongs_to :user, optional: true, inverse_of: :orders
  has_many :order_items, dependent: :destroy, inverse_of: :order
  has_many :items, through: :order_items
  has_many :order_promo_codes, dependent: :destroy, inverse_of: :order
  has_many :promo_codes, through: :order_promo_codes

  validates :total, :discount, :final_total, numericality: { greater_than_or_equal_to: 0 }
  validates_associated :order_promo_codes

  scope :placed, ->{ where(state: :confirmed) }

  accepts_nested_attributes_for :order_promo_codes, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :user, reject_if: :dup_user?

  before_update :update_total_and_discount

  # if user is already present in the system then consider that user. update the user info with the new info
  def dup_user?(attrs)
    if attrs[:email].present?
      u = User.find_by(email: attrs[:email])
      if u
        u.attributes = attrs
        self.user = u
        true
      else
        false
      end
    else
      false
    end
  end

  # Calculate the total, discount and final_total based on the order items and associated promo codes.
  def update_total_and_discount
    if order_items.any?
      self.total = order_items.collect(&:total_price).sum
      if order_promo_codes.any?
        ids = order_promo_codes.collect(&:promo_code_id)
        percentage_discount = PromoCode.where(id: ids, discount_type: :percentage).sum(:value)
        #percentage_discount = promo_codes.where(discount_type: :percentage).collect(&:value).sum
        self.discount = ((percentage_discount.to_f/100) * total)
        value_discount = PromoCode.where(id: ids, discount_type: :value).sum(:value)
        #value_discount = promo_codes.where(discount_type: :value).collect(&:value).sum
        self.discount = discount + value_discount
      else
        self.discount = 0
      end
      # discount is greater than total then final_total is 0. else total - discount
      self.final_total = discount > total ? 0 : total - discount
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.placed.page(params[:page])
  end

  def show
    @order = Order.find params[:id]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.haml
%h3
  Orders Placed
%table.table.table-bordered
  %thead
    %th Customer Email
    %th Total
    %th Discount
    %th Final Total
    %th Actions
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.user.email
        %td= order.total
        %td= order.discount
        %td= order.final_total
        %td= link_to 'View Details', order_path(order)

= paginate @orders

app/views/orders/show.html.haml
%h3 Order Details

Total: #{@order.total}
Discount: #{@order.discount}
Final Total: #{@order.final_total}

%br
Ordered Items
.row
  .col-md-8
    %table.table.table-bordered
      %thead
        %th Name
        %th Price
        %th Quantity
        %th Total Price
      %tbody
        - @order.order_items.includes(:item).each do |order_item|
          %tr{id: "order-item-#{order_item.id}"}
            %td= order_item.item.name
            %td= order_item.item.price
            %td= order_item.quantity
            %td= order_item.total_price

%br
Promo Codes Used:
.row
  .col-md-8
    %table.table.table-bordered
      %thead
        %th Code
        %th Description
      %tbody
        - @order.promo_codes.each do |code|
          %tr
            %td= code.code
            %td= code.description