config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show]
  resources :items, only: [:index] do
    member do
      put :add_to_basket
    end
  end

  resources :order_items, only: [:index, :edit, :update, :destroy]

  resource :basket, only: [:destroy, :update] do
    member do
      get :checkout
      get :payment
      put :process_payment
      put :check_discount
    end
  end

  root 'items#index'
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  name       :string
#  price      :decimal(8, 2)    default(0.0)
#  active     :boolean          default(TRUE)
#  discount   :decimal(8, 2)    default(0.0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Item < ApplicationRecord

  has_many :order_items

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :active, inclusion: { in: [true, false] }
  validates :discount, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @basket = current_basket
    @basket_items = @basket.items
    @items = Item.active.page(params[:page])
  end

  # Add the item to the basket if already not added.
  def add_to_basket
    item = Item.find(params[:id])
    basket = current_basket
    if basket.items.include? item
      redirect_to items_path, warning: 'Item already present in the basket' and return
    else
      basket.order_items.build({item: item})
      basket.valid?
      basket.save!
      session.destroy
      session[:order_id] = basket.id
      flash[:success] = 'Item has been added to the basket'
      redirect_to items_path and return
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def item_image(name)
    "#{name.downcase.gsub(' ', '-')}.jpg"
  end
end

app/views/items/index.html.haml
%h3
  Items
- @items.in_groups_of(3) do |group|
  .row
    - group.each do |item|
      - if item
        .col-md-4
          .well
            .image
              = image_tag item_image(item.name), class: 'img-responsive', alt: "Responsive image", style: 'height: 186px;'
            .data
              %strong #{item.name}
              .pull-right
                %strong #{item.price}
              %br
              - if @basket_items.include?(item)
                Present in the basket.
              - else
                = link_to 'Add to Basket', add_to_basket_item_path(item), method: :put
= paginate @items